{
 "title": "HS2 Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "HS2 Process CPU data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "hive_metrics_ProcessCpuLoad", "legendFormat": "__auto" },
    { "expr": "hive_metrics_ProcessCpuTime", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HS2 System CPU data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "hive_metrics_SystemCpuLoad", "legendFormat": "__auto" },
    { "expr": "hive_metrics_SystemLoadAverage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HS2 Physical Memory Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "hive_metrics_FreePhysicalMemorySize",
     "legendFormat": "__auto"
    },
    {
     "expr": "hive_metrics_TotalPhysicalMemorySize",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HS2 Virtual Memory Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "hive_metrics_CommittedVirtualMemorySize",
     "legendFormat": "__auto"
    },
    { "expr": "hive_metrics_FreeSwapSpaceSize", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HS2 Heap Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "hive_metrics_MemHeapCommittedM", "legendFormat": "__auto" },
    { "expr": "hive_metrics_MemHeapMaxM", "legendFormat": "__auto" },
    { "expr": "hive_metrics_MemHeapUsedM", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HS2 Non Heap Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "hive_metrics_MemNonHeapCommittedM",
     "legendFormat": "__auto"
    },
    { "expr": "hive_metrics_MemNonHeapMaxM", "legendFormat": "__auto" },
    { "expr": "hive_metrics_MemNonHeapUsedM", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HS2 Threads Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 24 },
   "targets": [
    { "expr": "hive_metrics_ThreadsBlocked", "legendFormat": "__auto" },
    { "expr": "hive_metrics_ThreadsNew", "legendFormat": "__auto" },
    { "expr": "hive_metrics_ThreadsRunnable", "legendFormat": "__auto" },
    { "expr": "hive_metrics_ThreadsTerminated", "legendFormat": "__auto" },
    {
     "expr": "hive_metrics_ThreadsTimedWaiting",
     "legendFormat": "__auto"
    },
    { "expr": "hive_metrics_ThreadsWaiting", "legendFormat": "__auto" }
   ]
  }
 ]
}